[project]
name = "research-repository-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "polars>=1.34.0",
    "scipy>=1.16.2",
]

[tool.uv]
package = true
